import { bn } from "../../../utils/big-number.utils";
import {
  TrackedStatType,
  type Trait,
  ProgressionId,
  type Upgrade,
  UpgradeIncrementType,
  UpgradeStat,
  UpgradeTarget,
} from "../types/progression.types";

export const BASE_UPGRADES: Upgrade[] = [
  {
    id: ProgressionId.ATTACK_DAMAGE,
    name: "Attack Damage",
    description: "Increase your attack damage",
    icon: "⚔️",
    upgradeTarget: UpgradeTarget.PLAYER,
    upgradedStat: UpgradeStat.ATTACK_DAMAGE,
    incrementType: UpgradeIncrementType.ADDITIVE,
    baseCost: 3,
    costMultiplier: 1.4,
    baseValue: 1,
    valueMultiplier: 1.3,
    maxLevel: 100,
  },
  {
    id: ProgressionId.HEALTH,
    name: "Health",
    description: "Increase your maximum health",
    icon: "❤️",
    upgradeTarget: UpgradeTarget.PLAYER,
    upgradedStat: UpgradeStat.MAX_HEALTH,
    incrementType: UpgradeIncrementType.ADDITIVE,
    baseCost: 5,
    costMultiplier: 1.4,
    baseValue: 3,
    valueMultiplier: 1.3,
    maxLevel: 100,
  },
];

export const TRAIT_UPGRADES: Upgrade[] = [
  // Tier 1
  {
    id: ProgressionId.SPIKY,
    name: "Spikes",
    description: "Increase attack damage by percentage",
    icon: "🦔",
    upgradeTarget: UpgradeTarget.PLAYER,
    upgradedStat: UpgradeStat.ATTACK_DAMAGE,
    incrementType: UpgradeIncrementType.PERCENTILE,
    baseCost: 20,
    costMultiplier: 1.6,
    baseValue: 20, // +20%
    valueMultiplier: 1.0, // No value scaling
    maxLevel: 10,
    unlockedByTrait: ProgressionId.SPIKY,
  },
  {
    id: ProgressionId.FLUFFY,
    name: "Fluf",
    description: "Increase attack speed by percentage",
    icon: "🦊",
    upgradeTarget: UpgradeTarget.PLAYER,
    upgradedStat: UpgradeStat.ATTACK_SPEED,
    incrementType: UpgradeIncrementType.PERCENTILE,
    baseCost: 50,
    costMultiplier: 1.8,
    baseValue: 10, // +10%
    valueMultiplier: 1.0,
    maxLevel: 5,
    unlockedByTrait: ProgressionId.FLUFFY,
  },
  {
    id: ProgressionId.SLIMY,
    name: "Slime",
    description: "Increase critical hit chance",
    icon: "💪",
    upgradeTarget: UpgradeTarget.PLAYER,
    upgradedStat: UpgradeStat.CRIT_CHANCE,
    incrementType: UpgradeIncrementType.PERCENTILE,
    baseCost: 50,
    costMultiplier: 1.3,
    baseValue: 2, // +2%
    valueMultiplier: 1.0,
    maxLevel: 10,
    unlockedByTrait: ProgressionId.SLIMY,
  },
  {
    id: ProgressionId.THICKER_SKIN,
    name: "Thicker Skin",
    description: "Multiply your maximum health",
    icon: "🛡️",
    upgradeTarget: UpgradeTarget.PLAYER,
    upgradedStat: UpgradeStat.MAX_HEALTH,
    incrementType: UpgradeIncrementType.MULTIPLICATIVE,
    baseCost: 100,
    costMultiplier: 1.8,
    baseValue: 1.2, // ×1.2
    valueMultiplier: 1.0,
    maxLevel: 5,
    unlockedByTrait: ProgressionId.THICKER_SKIN,
  },
  {
    id: ProgressionId.WARM_BLOODED,
    name: "Increase Temperature",
    description: "Increase energy gained from enemies",
    icon: "🔥",
    upgradeTarget: UpgradeTarget.PLAYER,
    upgradedStat: UpgradeStat.ENERGY_BONUS,
    incrementType: UpgradeIncrementType.PERCENTILE,
    baseCost: 150,
    costMultiplier: 1.7,
    baseValue: 10, // +10%
    valueMultiplier: 1.0,
    maxLevel: 10,
    unlockedByTrait: ProgressionId.WARM_BLOODED,
  },
  {
    id: ProgressionId.TEETHY,
    name: "Teeth",
    description: "Increase energy gained from enemies",
    icon: "🔥",
    upgradeTarget: UpgradeTarget.PLAYER,
    upgradedStat: UpgradeStat.ENERGY_BONUS,
    incrementType: UpgradeIncrementType.PERCENTILE,
    baseCost: 150,
    costMultiplier: 1.7,
    baseValue: 10, // +10%
    valueMultiplier: 1.0,
    maxLevel: 10,
    unlockedByTrait: ProgressionId.TEETHY,
  },
  // Tier 2
  {
    id: ProgressionId.CHEESY,
    name: "Stinky",
    description: "Increase energy gained from enemies",
    icon: "🔥",
    upgradeTarget: UpgradeTarget.PLAYER,
    upgradedStat: UpgradeStat.ENERGY_BONUS,
    incrementType: UpgradeIncrementType.PERCENTILE,
    baseCost: 150,
    costMultiplier: 1.7,
    baseValue: 10, // +10%
    valueMultiplier: 1.0,
    maxLevel: 10,
    unlockedByTrait: ProgressionId.CHEESY,
  },
  {
    id: ProgressionId.METAL_SHELLED,
    name: "Metal Shell",
    description: "Increase energy gained from enemies",
    icon: "🔥",
    upgradeTarget: UpgradeTarget.PLAYER,
    upgradedStat: UpgradeStat.ENERGY_BONUS,
    incrementType: UpgradeIncrementType.PERCENTILE,
    baseCost: 150,
    costMultiplier: 1.7,
    baseValue: 10, // +10%
    valueMultiplier: 1.0,
    maxLevel: 10,
    unlockedByTrait: ProgressionId.METAL_SHELLED,
  },
  {
    id: ProgressionId.MORE_TEETH,
    name: "More Teeth",
    description: "Increase energy gained from enemies",
    icon: "🔥",
    upgradeTarget: UpgradeTarget.PLAYER,
    upgradedStat: UpgradeStat.ENERGY_BONUS,
    incrementType: UpgradeIncrementType.PERCENTILE,
    baseCost: 150,
    costMultiplier: 1.7,
    baseValue: 10, // +10%
    valueMultiplier: 1.0,
    maxLevel: 10,
    unlockedByTrait: ProgressionId.MORE_TEETH,
  },
  {
    id: ProgressionId.TAIL,
    name: "Tail",
    description: "Increase energy gained from enemies",
    icon: "🔥",
    upgradeTarget: UpgradeTarget.PLAYER,
    upgradedStat: UpgradeStat.ENERGY_BONUS,
    incrementType: UpgradeIncrementType.PERCENTILE,
    baseCost: 150,
    costMultiplier: 1.7,
    baseValue: 10, // +10%
    valueMultiplier: 1.0,
    maxLevel: 10,
    unlockedByTrait: ProgressionId.TAIL,
  },
  {
    id: ProgressionId.MUDDY,
    name: "Muddy",
    description: "Increase energy gained from enemies",
    icon: "🔥",
    upgradeTarget: UpgradeTarget.PLAYER,
    upgradedStat: UpgradeStat.ENERGY_BONUS,
    incrementType: UpgradeIncrementType.PERCENTILE,
    baseCost: 150,
    costMultiplier: 1.7,
    baseValue: 10, // +10%
    valueMultiplier: 1.0,
    maxLevel: 10,
    unlockedByTrait: ProgressionId.MUDDY,
  },
  {
    id: ProgressionId.BETTER_VISION,
    name: "Increase Vision",
    description: "Increase energy gained from enemies",
    icon: "🔥",
    upgradeTarget: UpgradeTarget.PLAYER,
    upgradedStat: UpgradeStat.ENERGY_BONUS,
    incrementType: UpgradeIncrementType.PERCENTILE,
    baseCost: 150,
    costMultiplier: 1.7,
    baseValue: 10, // +10%
    valueMultiplier: 1.0,
    maxLevel: 10,
    unlockedByTrait: ProgressionId.BETTER_VISION,
  },
];

export const ALL_UPGRADES: Upgrade[] = [...BASE_UPGRADES, ...TRAIT_UPGRADES];

export const TRAITS: Trait[] = [
  // Tier 1
  {
    id: ProgressionId.SPIKY,
    name: "Spiky",
    description: "Slay a total of 50 enemies",
    icon: "🦔",
    tier: 1,
    trackedStat: TrackedStatType.TOTAL_ENEMIES_KILLED,
    goalValue: bn("1.35e8"),
    linkedUpgrade: ProgressionId.SPIKY,
  },
  {
    id: ProgressionId.FLUFFY,
    name: "Fluffy",
    description: "Slay 30 Red Fox enemies",
    icon: "🦊",
    tier: 1,
    trackedStat: TrackedStatType.SPECIFIC_ENEMY_KILLED,
    trackedEnemyName: "Red fox",
    goalValue: bn(30),
    linkedUpgrade: ProgressionId.FLUFFY,
  },
  {
    id: ProgressionId.SLIMY,
    name: "Generate slime",
    description: "Deal 20 damage in a single hit",
    icon: "💪",
    tier: 1,
    trackedStat: TrackedStatType.HIGHEST_SINGLE_HIT,
    goalValue: bn(20),
    linkedUpgrade: ProgressionId.SLIMY,
  },
  {
    id: ProgressionId.THICKER_SKIN,
    name: "Thicker Skin",
    description: "Take a total of 500 damage",
    icon: "🛡️",
    tier: 1,
    trackedStat: TrackedStatType.TOTAL_DAMAGE_TAKEN,
    goalValue: bn(500),
    linkedUpgrade: ProgressionId.THICKER_SKIN,
  },
  {
    id: ProgressionId.WARM_BLOODED,
    name: "Warm Blooded",
    description: "Gain a total of 200 energy",
    icon: "🔥",
    tier: 1,
    trackedStat: TrackedStatType.TOTAL_ENERGY_GAINED,
    goalValue: bn(200),
    linkedUpgrade: ProgressionId.WARM_BLOODED,
  },
  {
    id: ProgressionId.TEETHY,
    name: "Teethy",
    description: "Gain a total of 200 energy",
    icon: "🔥",
    tier: 1,
    trackedStat: TrackedStatType.TOTAL_ENERGY_GAINED,
    goalValue: bn(200),
    linkedUpgrade: ProgressionId.TEETHY,
  },
  // Tier 2
  {
    id: ProgressionId.CHEESY,
    name: "Cheesy",
    description: "Gain a total of 200 energy",
    icon: "🔥",
    tier: 2,
    trackedStat: TrackedStatType.TOTAL_ENERGY_GAINED,
    goalValue: bn(200),
    linkedUpgrade: ProgressionId.CHEESY,
  },
  {
    id: ProgressionId.METAL_SHELLED,
    name: "Metal Shelled",
    description: "Gain a total of 200 energy",
    icon: "🔥",
    tier: 2,
    trackedStat: TrackedStatType.TOTAL_ENERGY_GAINED,
    goalValue: bn(200),
    linkedUpgrade: ProgressionId.METAL_SHELLED,
  },
  {
    id: ProgressionId.MORE_TEETH,
    name: "More Teeth",
    description: "Gain a total of 200 energy",
    icon: "🔥",
    tier: 2,
    trackedStat: TrackedStatType.TOTAL_ENERGY_GAINED,
    goalValue: bn(200),
    linkedUpgrade: ProgressionId.MORE_TEETH,
  },
  {
    id: ProgressionId.TAIL,
    name: "Tail",
    description: "Gain a total of 200 energy",
    icon: "🔥",
    tier: 2,
    trackedStat: TrackedStatType.TOTAL_ENERGY_GAINED,
    goalValue: bn(200),
    linkedUpgrade: ProgressionId.TAIL,
  },
  {
    id: ProgressionId.MUDDY,
    name: "Muddy",
    description: "Gain a total of 200 energy",
    icon: "🔥",
    tier: 2,
    trackedStat: TrackedStatType.TOTAL_ENERGY_GAINED,
    goalValue: bn(200),
    linkedUpgrade: ProgressionId.MUDDY,
  },
  {
    id: ProgressionId.BETTER_VISION,
    name: "Better Vision",
    description: "Gain a total of 200 energy",
    icon: "🔥",
    tier: 2,
    trackedStat: TrackedStatType.TOTAL_ENERGY_GAINED,
    goalValue: bn(200),
    linkedUpgrade: ProgressionId.BETTER_VISION,
  },
];

export function getTraitsByTier(tier: number): Trait[] {
  return TRAITS.filter((trait) => trait.tier === tier);
}

export function getUpgradeById(id: ProgressionId): Upgrade | undefined {
  return ALL_UPGRADES.find((upgrade) => upgrade.id === id);
}

export function getTraitById(id: ProgressionId): Trait | undefined {
  return TRAITS.find((trait) => trait.id === id);
}
