export const PLAYER_CONFIG = {
  BASE_HEALTH: 50,
  BASE_ATTACK_DAMAGE: 1,
  BASE_ATTACK_SPEED: 1, // 1 attack per second
  BASE_CRITICAL_CHANCE: 0,
  BASE_SHIELD: 0,
} as const;

export const BASE_PLAYER_STATS = {
  name: "Hero",
  maxHealth: PLAYER_CONFIG.BASE_HEALTH,
  currentHealth: PLAYER_CONFIG.BASE_HEALTH,
  attackDamage: PLAYER_CONFIG.BASE_ATTACK_DAMAGE,
  attackSpeed: PLAYER_CONFIG.BASE_ATTACK_SPEED,
  critChance: PLAYER_CONFIG.BASE_CRITICAL_CHANCE,
  shield: PLAYER_CONFIG.BASE_SHIELD,
};
