import { EnemyRarity, EnemyType } from "../types/enemy.types";
import { getEnemyBaseStats } from "../helpers/get-enemy-base-stats.helper";
import type { Enemy } from "../../combat/types/combat.types";

export const ENEMY_LIST_AREA_1: Record<string, Enemy> = {
  GRASSHOPPER: getEnemyBaseStats({
    name: "Grasshopper",
    description: "A small and quick enemy.",
    areaNumber: 1,
    rarity: EnemyRarity.COMMON,
    type: EnemyType.FAST,
    sprite: "/enemy/Snail1.png",
    icon: "/enemy/Snail1.png",
  }),
  SNAIL: getEnemyBaseStats({
    name: "Snail",
    description: "A small and quick enemy.",
    areaNumber: 1,
    rarity: EnemyRarity.COMMON,
    type: EnemyType.TANK,
    sprite: "/enemy/Snail1.png",
    icon: "/enemy/Snail1.png",
  }),
  FIELD_MOUSE: getEnemyBaseStats({
    name: "Field mouse",
    description: "A standard enemy.",
    areaNumber: 1,
    rarity: EnemyRarity.UNCOMMON,
    type: EnemyType.STANDARD,
    sprite: "/enemy/Mouse1.png",
    icon: "/enemy/Mouse1.png",
  }),
  WILD_RABBIT: getEnemyBaseStats({
    name: "Wild rabbit",
    description: "A more strong enemy.",
    areaNumber: 1,
    rarity: EnemyRarity.UNCOMMON,
    type: EnemyType.STRONG,
    sprite: "/enemy/Rabbit1.png",
    icon: "/enemy/Rabbit1.png",
  }),
  RED_FOX: getEnemyBaseStats({
    name: "Red fox",
    description: "A more strong enemy.",
    areaNumber: 1,
    rarity: EnemyRarity.RARE,
    type: EnemyType.STRONG,
    sprite: "/enemy/RedFox1.png",
    icon: "/enemy/RedFox1.png",
  }),
};

export const ENEMY_LIST_AREA_2: Record<string, Enemy> = {
  SEWER_RAT: getEnemyBaseStats({
    name: "Sewer rat",
    description: "A small and quick enemy.",
    areaNumber: 2,
    rarity: EnemyRarity.COMMON,
    type: EnemyType.FAST,
    sprite: "/enemy/Snail1.png",
    icon: "/enemy/Snail1.png",
  }),
  COCKROACH: getEnemyBaseStats({
    name: "Cockroach",
    description: "A small and quick enemy.",
    areaNumber: 2,
    rarity: EnemyRarity.COMMON,
    type: EnemyType.TANK,
    sprite: "/enemy/Snail1.png",
    icon: "/enemy/Snail1.png",
  }),
  MUTANT_RACCOON: getEnemyBaseStats({
    name: "Mutant raccoon",
    description: "A standard enemy.",
    areaNumber: 2,
    rarity: EnemyRarity.UNCOMMON,
    type: EnemyType.STANDARD,
    sprite: "/enemy/Snail1.png",
    icon: "/enemy/Snail1.png",
  }),
  FERAL_DOG: getEnemyBaseStats({
    name: "Feral dog",
    description: "A more strong enemy.",
    areaNumber: 2,
    rarity: EnemyRarity.UNCOMMON,
    type: EnemyType.STRONG,
    sprite: "/enemy/Snail1.png",
    icon: "/enemy/Snail1.png",
  }),
  WASTE_ALLIGATOR: getEnemyBaseStats({
    name: "Waste alligator",
    description: "A more strong enemy.",
    areaNumber: 2,
    rarity: EnemyRarity.RARE,
    type: EnemyType.STRONG,
    sprite: "/enemy/Snail1.png",
    icon: "/enemy/Snail1.png",
  }),
};

export const ENEMY_LIST_AREA_3: Record<string, Enemy> = {
  THORN_BUSH: getEnemyBaseStats({
    name: "Thorn Bush",
    description: "A more strong enemy.",
    areaNumber: 2,
    rarity: EnemyRarity.COMMON,
    type: EnemyType.STRONG,
    sprite: "/enemy/Snail1.png",
    icon: "/enemy/Snail1.png",
  }),
  VINE_CREEPER: getEnemyBaseStats({
    name: "Carnivorous Plant",
    description: "A standard enemy.",
    areaNumber: 2,
    rarity: EnemyRarity.COMMON,
    type: EnemyType.STANDARD,
    sprite: "/enemy/Snail1.png",
    icon: "/enemy/Snail1.png",
  }),
  CARNIVOROUS_PLANT: getEnemyBaseStats({
    name: "Carnivorous Plant",
    description: "A standard enemy.",
    areaNumber: 2,
    rarity: EnemyRarity.UNCOMMON,
    type: EnemyType.STANDARD,
    sprite: "/enemy/Snail1.png",
    icon: "/enemy/Snail1.png",
  }),
  POISON_IVY_SERPENT: getEnemyBaseStats({
    name: "Carnivorous Plant",
    description: "A standard enemy.",
    areaNumber: 2,
    rarity: EnemyRarity.UNCOMMON,
    type: EnemyType.STANDARD,
    sprite: "/enemy/Snail1.png",
    icon: "/enemy/Snail1.png",
  }),
  ANCIENT_TREANT: getEnemyBaseStats({
    name: "Ancient Treant",
    description: "A more tanky enemy.",
    areaNumber: 2,
    rarity: EnemyRarity.RARE,
    type: EnemyType.TANK,
    sprite: "/enemy/Snail1.png",
    icon: "/enemy/Snail1.png",
  }),
};
